# Generated by Django 5.1.5 on 2026-04-28 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CAREER', 'Career Pilot'), ('QUESTION_GEN', 'Question Generator'), ('ADAPTIVE_NEXT', 'Adaptive Next Question'), ('CONTENT_SEARCH', 'Content Search')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('request_json', models.JSONField()),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_in', models.PositiveIntegerField(null=True)),
                ('tokens_out', models.PositiveIntegerField(null=True)),
                ('cost_inr', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('duration_ms', models.PositiveIntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='ai_bridge_a_school__5d4854_idx'), models.Index(fields=['school', 'kind', 'status'], name='ai_bridge_a_school__44f7fa_idx'), models.Index(fields=['created_by', 'kind'], name='ai_bridge_a_created_ba6bb0_idx')],
            },
        ),
    ]
